travis:
  secure:
    BINSTAR_TOKEN: CK3xvn0RmWqmsIWLqcPm7GdNVlUR9o0t0l+NobjOvZXMr0/aaxul5uhUa/qUYZQKospz5n0FYTwvStM0GPgxDjfDKDzV1XowxcAN86QIq9bUrcqyGVrSeG/PwKL3cLyn4HrHsU0mXYSPm0Oxd+3dcqpzKIYCTxnv1en81hEte4vVNlp5itaV31LUSdpaAV5zJP0Wk0jYFFGUFGpg29iPUP3HeiRY11esTFmHD/53I0/9hqNFTtNvxwtU+FlLh8nMBaGFG2b3lD3qa6Xk4DWuzU8YIE4bK3NFmmT2HfmRp0oehJhYi394EdrbfdIfzHEvnHouiNep3uJw/5sc1V6AQ48VjDXlOKP1EMo+7WAbcb8LUZ4KE0Oq0tN7AIq3HkNaDWtSOJGoideNe1ODoaCdakd+/gLksOp+vPbJC6t9SeIzC+VNSrWUt6G/mmS8yNsFquIw+BHwBgPIWk9d9CKBeJVoqpdR1uTJFPGw66W6i/1AzFCbjmdlmX2B/+KVy40IPOoLSfhDRGYOohwutiR8NhZoZGcJSIdf0aHHslTK373WXFA7Lh3AfTKPD2A8LEXBTReuOJv4QfIkRwanUdHTQyt7xujSULAQvYCbwBbyIkhYSEmy0EJxdDK2+h3ZYNjMu4FMp+lJyxKiT43kABNhMbpa/N4pHNVGhmwixmUxyM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
